package com.lazz.ui.model;
// Generated Jul 22, 2018 7:33:01 PM by Hibernate Tools 5.2.10.Final

/**
 * InvoiceDetails generated by hbm2java
 */
public class InvoiceDetailsModel  {

	private Integer invcDtId;
	private InvoiceModel invoice;
	private ProdCfgModel prodCfg;
	private ProductsModel products;

	public InvoiceDetailsModel() {
	}

	public InvoiceDetailsModel(InvoiceModel invoice) {
		this.invoice = invoice;
	}

	public InvoiceDetailsModel(InvoiceModel invoice, ProdCfgModel prodCfg, ProductsModel products) {
		this.invoice = invoice;
		this.prodCfg = prodCfg;
		this.products = products;
	}

	public Integer getInvcDtId() {
		return this.invcDtId;
	}

	public void setInvcDtId(Integer invcDtId) {
		this.invcDtId = invcDtId;
	}

	public InvoiceModel getInvoice() {
		return this.invoice;
	}

	public void setInvoice(InvoiceModel invoice) {
		this.invoice = invoice;
	}

	public ProdCfgModel getProdCfg() {
		return this.prodCfg;
	}

	public void setProdCfg(ProdCfgModel prodCfg) {
		this.prodCfg = prodCfg;
	}

	public ProductsModel getProducts() {
		return this.products;
	}

	public void setProducts(ProductsModel products) {
		this.products = products;
	}

}
