package com.lazz.ui.model;
// Generated Jul 22, 2018 7:33:01 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Invoice generated by hbm2java
 */
public class InvoiceModel  {

	private Integer invcId;
	private Date invcDt;
	private int usrId;
	private String invcStage;
	private int invcAccptBy;
	private Date invcAccptDt;
	private String invcShipmentAdd1;
	private String invcShipmentAdd2;
	private String invcShipmentPostCode;
	private String invcRecptMob;
	private String invcRecptEmail;
	private Date invcCrtdDt;
	private Date invcUptdDt;
	private float invcAmt;
	private Float invcDis;
	private Set<InvoiceDetailsModel> invoiceDetailses = new HashSet<InvoiceDetailsModel>(0);

	public InvoiceModel() {
	}

	public InvoiceModel(Date invcDt, int usrId, String invcStage, int invcAccptBy, Date invcAccptDt, Date invcCrtdDt,
			Date invcUptdDt, float invcAmt) {
		this.invcDt = invcDt;
		this.usrId = usrId;
		this.invcStage = invcStage;
		this.invcAccptBy = invcAccptBy;
		this.invcAccptDt = invcAccptDt;
		this.invcCrtdDt = invcCrtdDt;
		this.invcUptdDt = invcUptdDt;
		this.invcAmt = invcAmt;
	}

	public InvoiceModel(Date invcDt, int usrId, String invcStage, int invcAccptBy, Date invcAccptDt, String invcShipmentAdd1,
			String invcShipmentAdd2, String invcShipmentPostCode, String invcRecptMob, String invcRecptEmail,
			Date invcCrtdDt, Date invcUptdDt, float invcAmt, Float invcDis, Set invoiceDetailses) {
		this.invcDt = invcDt;
		this.usrId = usrId;
		this.invcStage = invcStage;
		this.invcAccptBy = invcAccptBy;
		this.invcAccptDt = invcAccptDt;
		this.invcShipmentAdd1 = invcShipmentAdd1;
		this.invcShipmentAdd2 = invcShipmentAdd2;
		this.invcShipmentPostCode = invcShipmentPostCode;
		this.invcRecptMob = invcRecptMob;
		this.invcRecptEmail = invcRecptEmail;
		this.invcCrtdDt = invcCrtdDt;
		this.invcUptdDt = invcUptdDt;
		this.invcAmt = invcAmt;
		this.invcDis = invcDis;
		this.invoiceDetailses = invoiceDetailses;
	}

	public Integer getInvcId() {
		return this.invcId;
	}

	public void setInvcId(Integer invcId) {
		this.invcId = invcId;
	}

	public Date getInvcDt() {
		return this.invcDt;
	}

	public void setInvcDt(Date invcDt) {
		this.invcDt = invcDt;
	}

	public int getUsrId() {
		return this.usrId;
	}

	public void setUsrId(int usrId) {
		this.usrId = usrId;
	}

	public String getInvcStage() {
		return this.invcStage;
	}

	public void setInvcStage(String invcStage) {
		this.invcStage = invcStage;
	}

	public int getInvcAccptBy() {
		return this.invcAccptBy;
	}

	public void setInvcAccptBy(int invcAccptBy) {
		this.invcAccptBy = invcAccptBy;
	}

	public Date getInvcAccptDt() {
		return this.invcAccptDt;
	}

	public void setInvcAccptDt(Date invcAccptDt) {
		this.invcAccptDt = invcAccptDt;
	}

	public String getInvcShipmentAdd1() {
		return this.invcShipmentAdd1;
	}

	public void setInvcShipmentAdd1(String invcShipmentAdd1) {
		this.invcShipmentAdd1 = invcShipmentAdd1;
	}

	public String getInvcShipmentAdd2() {
		return this.invcShipmentAdd2;
	}

	public void setInvcShipmentAdd2(String invcShipmentAdd2) {
		this.invcShipmentAdd2 = invcShipmentAdd2;
	}

	public String getInvcShipmentPostCode() {
		return this.invcShipmentPostCode;
	}

	public void setInvcShipmentPostCode(String invcShipmentPostCode) {
		this.invcShipmentPostCode = invcShipmentPostCode;
	}

	public String getInvcRecptMob() {
		return this.invcRecptMob;
	}

	public void setInvcRecptMob(String invcRecptMob) {
		this.invcRecptMob = invcRecptMob;
	}

	public String getInvcRecptEmail() {
		return this.invcRecptEmail;
	}

	public void setInvcRecptEmail(String invcRecptEmail) {
		this.invcRecptEmail = invcRecptEmail;
	}

	public Date getInvcCrtdDt() {
		return this.invcCrtdDt;
	}

	public void setInvcCrtdDt(Date invcCrtdDt) {
		this.invcCrtdDt = invcCrtdDt;
	}

	public Date getInvcUptdDt() {
		return this.invcUptdDt;
	}

	public void setInvcUptdDt(Date invcUptdDt) {
		this.invcUptdDt = invcUptdDt;
	}

	public float getInvcAmt() {
		return this.invcAmt;
	}

	public void setInvcAmt(float invcAmt) {
		this.invcAmt = invcAmt;
	}

	public Float getInvcDis() {
		return this.invcDis;
	}

	public void setInvcDis(Float invcDis) {
		this.invcDis = invcDis;
	}

	public Set<InvoiceDetailsModel> getInvoiceDetailses() {
		return this.invoiceDetailses;
	}

	public void setInvoiceDetailses(Set<InvoiceDetailsModel> invoiceDetailses) {
		this.invoiceDetailses = invoiceDetailses;
	}

}
