package com.lazz.ui.model;
// Generated Jul 22, 2018 7:33:01 PM by Hibernate Tools 5.2.10.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.lazz.service.domain.UserGroups;

/**
 * PrdPriceRules generated by hbm2java
 */
public class PrdPriceRulesModel  {

	private Integer prdPrcRuleId;
	private ProdCfgModel prodCfg;
	private Integer prdPrcRuleCarton;
	private Float prdPrcRulePriceWest;
	private Float prdPrcRulePriceEast;
	private Date prdPrcRulePriceCrtdDt;
	private Date prdPrcRulePriceUptdDt;
	private List<UserGroups> userGroups = new ArrayList<UserGroups>(0);
	
	public PrdPriceRulesModel() {
	}

	public Integer getPrdPrcRuleId() {
		return this.prdPrcRuleId;
	}

	public void setPrdPrcRuleId(Integer prdPrcRuleId) {
		this.prdPrcRuleId = prdPrcRuleId;
	}

	public ProdCfgModel getProdCfg() {
		return this.prodCfg;
	}

	public void setProdCfg(ProdCfgModel prodCfg) {
		this.prodCfg = prodCfg;
	}

	public Integer getPrdPrcRuleCarton() {
		return this.prdPrcRuleCarton;
	}

	public void setPrdPrcRuleCarton(Integer prdPrcRuleCarton) {
		this.prdPrcRuleCarton = prdPrcRuleCarton;
	}

	public Float getPrdPrcRulePriceWest() {
		return this.prdPrcRulePriceWest;
	}

	public void setPrdPrcRulePriceWest(Float prdPrcRulePriceWest) {
		this.prdPrcRulePriceWest = prdPrcRulePriceWest;
	}

	public Float getPrdPrcRulePriceEast() {
		return this.prdPrcRulePriceEast;
	}

	public void setPrdPrcRulePriceEast(Float prdPrcRulePriceEast) {
		this.prdPrcRulePriceEast = prdPrcRulePriceEast;
	}

	public Date getPrdPrcRulePriceCrtdDt() {
		return this.prdPrcRulePriceCrtdDt;
	}

	public void setPrdPrcRulePriceCrtdDt(Date prdPrcRulePriceCrtdDt) {
		this.prdPrcRulePriceCrtdDt = prdPrcRulePriceCrtdDt;
	}

	public Date getPrdPrcRulePriceUptdDt() {
		return this.prdPrcRulePriceUptdDt;
	}

	public void setPrdPrcRulePriceUptdDt(Date prdPrcRulePriceUptdDt) {
		this.prdPrcRulePriceUptdDt = prdPrcRulePriceUptdDt;
	}


	public List<UserGroups> getUserGroups() {
		return userGroups;
	}

	public void setUserGroups(List<UserGroups> userGroups) {
		this.userGroups = userGroups;
	}

	
}
