package com.lazz.ui.model;
// Generated Jul 22, 2018 7:33:01 PM by Hibernate Tools 5.2.10.Final

import java.util.ArrayList;
import java.util.List;

/**
 * ProdCfg generated by hbm2java
 */
public class ProdCfgModel  {

	/*private Integer prdCfgId;
	private ProductsModel products;
	private UserGroupsModel userGroups;
	private Date prdCfgUptdDt;

	public Integer getPrdCfgId() {
		return this.prdCfgId;
	}

	public void setPrdCfgId(Integer prdCfgId) {
		this.prdCfgId = prdCfgId;
	}

	public ProductsModel getProducts() {
		return this.products;
	}

	public void setProducts(ProductsModel products) {
		this.products = products;
	}

	public UserGroupsModel getUserGroups() {
		return this.userGroups;
	}

	public void setUserGroups(UserGroupsModel userGroups) {
		this.userGroups = userGroups;
	}

	public Date getPrdCfgUptdDt() {
		return this.prdCfgUptdDt;
	}

	public void setPrdCfgUptdDt(Date prdCfgUptdDt) {
		this.prdCfgUptdDt = prdCfgUptdDt;
	}
*/
	private Integer prdId;
	private String prdName;
	private Integer prdCfgId;
	private List<UserGroupsModel> userGroups = new ArrayList<UserGroupsModel>(0); 
	private List<String> selectedUserGroups;
	private List<ProdCfgModel> prodCfgList;
	private ProductsModel product;
	private List<PrdPriceRulesModel> prdPriceRules = new ArrayList<PrdPriceRulesModel>(0);
	
	public Integer getPrdId() {
		return prdId;
	}
	public void setPrdId(Integer prdId) {
		this.prdId = prdId;
	}
	public String getPrdName() {
		return prdName;
	}
	public void setPrdName(String prdName) {
		this.prdName = prdName;
	}
	public List<UserGroupsModel> getUserGroups() {
		return userGroups;
	}
	public void setUserGroups(List<UserGroupsModel> userGroups) {
		this.userGroups = userGroups;
	}
	public List<String> getSelectedUserGroups() {
		return selectedUserGroups;
	}
	public void setSelectedUserGroups(List<String> selectedUserGroups) {
		this.selectedUserGroups = selectedUserGroups;
	}
	/*public ProdCfgModel convertDomainToModel(ProdCfg domain) {
		ProdCfgModel model = new ProdCfgModel();
		model.
	}*/
	public List<ProdCfgModel> getProdCfgList() {
		return prodCfgList;
	}
	public void setProdCfgList(List<ProdCfgModel> prodCfgList) {
		this.prodCfgList = prodCfgList;
	}
	public ProductsModel getProduct() {
		return product;
	}
	public void setProduct(ProductsModel product) {
		this.product = product;
	}
	public List<PrdPriceRulesModel> getPrdPriceRules() {
		return prdPriceRules;
	}
	public void setPrdPriceRules(List<PrdPriceRulesModel> prdPriceRules) {
		this.prdPriceRules = prdPriceRules;
	}
	public Integer getPrdCfgId() {
		return prdCfgId;
	}
	public void setPrdCfgId(Integer prdCfgId) {
		this.prdCfgId = prdCfgId;
	}
	
}
