package com.lazz.ui.model;
// Generated Jul 22, 2018 7:33:01 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
public class UsersModel implements java.io.Serializable {

	private Integer usrId;
	private UserGroupsModel userGroups;
	private UserTypesModel userTypes;
	private UsersModel users;
	private String usrName;
	private String usrPassword;
	private String usrConfirmPassword;
	private Date usrCrtdDt;
	private Date usrUptdDt;
	private Set<UsersModel> userses = new HashSet<UsersModel>(0);
	private UserDetailsModel userDetails;

	public Integer getUsrId() {
		return this.usrId;
	}

	public void setUsrId(Integer usrId) {
		this.usrId = usrId;
	}

	public UserGroupsModel getUserGroups() {
		return this.userGroups;
	}

	public void setUserGroups(UserGroupsModel userGroups) {
		this.userGroups = userGroups;
	}

	public UserTypesModel getUserTypes() {
		return this.userTypes;
	}

	public void setUserTypes(UserTypesModel userTypes) {
		this.userTypes = userTypes;
	}

	public UsersModel getUsers() {
		return this.users;
	}

	public void setUsers(UsersModel users) {
		this.users = users;
	}

	public String getUsrName() {
		return this.usrName;
	}

	public void setUsrName(String usrName) {
		this.usrName = usrName;
	}

	public String getUsrPassword() {
		return this.usrPassword;
	}

	public void setUsrPassword(String usrPassword) {
		this.usrPassword = usrPassword;
	}

	public Date getUsrCrtdDt() {
		return this.usrCrtdDt;
	}

	public void setUsrCrtdDt(Date usrCrtdDt) {
		this.usrCrtdDt = usrCrtdDt;
	}

	public Date getUsrUptdDt() {
		return this.usrUptdDt;
	}

	public void setUsrUptdDt(Date usrUptdDt) {
		this.usrUptdDt = usrUptdDt;
	}

	public Set<UsersModel> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<UsersModel> userses) {
		this.userses = userses;
	}

	public UserDetailsModel getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetailsModel userDetails) {
		this.userDetails = userDetails;
	}

	public String getUsrConfirmPassword() {
		return usrConfirmPassword;
	}

	public void setUsrConfirmPassword(String usrConfirmPassword) {
		this.usrConfirmPassword = usrConfirmPassword;
	}
	
}
