package com.lazz.ui.model;
// Generated Jul 22, 2018 7:33:01 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;

/**
 * UserTypes generated by hbm2java
 */
public class UserTypesModel implements java.io.Serializable {

	private Integer utId;
	private String utName;
	private String utDesc;
	private Set<UsersModel> userses = new HashSet<UsersModel>(0);

	public UserTypesModel() {
	}

	public UserTypesModel(String utName) {
		this.utName = utName;
	}

	public UserTypesModel(String utName, String utDesc, Set userses) {
		this.utName = utName;
		this.utDesc = utDesc;
		this.userses = userses;
	}

	public Integer getUtId() {
		return this.utId;
	}

	public void setUtId(Integer utId) {
		this.utId = utId;
	}

	public String getUtName() {
		return this.utName;
	}

	public void setUtName(String utName) {
		this.utName = utName;
	}

	public String getUtDesc() {
		return this.utDesc;
	}

	public void setUtDesc(String utDesc) {
		this.utDesc = utDesc;
	}

	public Set<UsersModel> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<UsersModel> userses) {
		this.userses = userses;
	}

}
