package com.lazz.ui.model;
// Generated Jul 22, 2018 7:33:01 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.lazz.service.domain.ProdCfg;
import com.lazz.service.domain.UserGroups;

/**
 * UserGroups generated by hbm2java
 */
public class UserGroupsModel implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer usrGrpId;
	private String usrGrpName;
	private String usrGrpDesc;
	private Date usrCrtdDt;
	private Date usrUptdDt;
	private String assignedToProduct = "N";
	private Set<ProdCfgModel> prodCfgs = new HashSet<ProdCfgModel>(0);
	private Set<UsersModel> userses = new HashSet<UsersModel>(0);

	/*public UserGroupsModel() {
	}

	public UserGroupsModel(String usrGrpName, Date usrCrtdDt, Date usrUptdDt) {
		this.usrGrpName = usrGrpName;
		this.usrCrtdDt = usrCrtdDt;
		this.usrUptdDt = usrUptdDt;
	}*/

	/*public UserGroups(String usrGrpName, String usrGrpDesc, Date usrCrtdDt, Date usrUptdDt, Set prodCfgs, Set userses) {
		this.usrGrpName = usrGrpName;
		this.usrGrpDesc = usrGrpDesc;
		this.usrCrtdDt = usrCrtdDt;
		this.usrUptdDt = usrUptdDt;
		this.prodCfgs = prodCfgs;
		this.userses = userses;
	}*/
	
	/*public UserGroupsModel(String usrGrpName, String usrGrpDesc, Date usrCrtdDt, Date usrUptdDt, Set prodCfgs) {
		this.usrGrpName = usrGrpName;
		this.usrGrpDesc = usrGrpDesc;
		this.usrCrtdDt = usrCrtdDt;
		this.usrUptdDt = usrUptdDt;
		//this.prodCfgs = prodCfgs;
		this.userses = userses;
	}*/


	public Integer getUsrGrpId() {
		return this.usrGrpId;
	}

	public void setUsrGrpId(Integer usrGrpId) {
		this.usrGrpId = usrGrpId;
	}

	public String getUsrGrpName() {
		return this.usrGrpName;
	}

	public void setUsrGrpName(String usrGrpName) {
		this.usrGrpName = usrGrpName;
	}

	public String getUsrGrpDesc() {
		return this.usrGrpDesc;
	}

	public void setUsrGrpDesc(String usrGrpDesc) {
		this.usrGrpDesc = usrGrpDesc;
	}

	public Date getUsrCrtdDt() {
		return this.usrCrtdDt;
	}

	public void setUsrCrtdDt(Date usrCrtdDt) {
		this.usrCrtdDt = usrCrtdDt;
	}

	public Date getUsrUptdDt() {
		return this.usrUptdDt;
	}

	public void setUsrUptdDt(Date usrUptdDt) {
		this.usrUptdDt = usrUptdDt;
	}

	public Set<ProdCfgModel> getProdCfgs() {
		return this.prodCfgs;
	}

	public void setProdCfgs(Set<ProdCfgModel> prodCfgs) {
		this.prodCfgs = prodCfgs;
	}

	public Set<UsersModel> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<UsersModel> userses) {
		this.userses = userses;
	}

	public String getAssignedToProduct() {
		return assignedToProduct;
	}

	public void setAssignedToProduct(String assignedToProduct) {
		this.assignedToProduct = assignedToProduct;
	}
	
	public UserGroupsModel convertDomainToModel(UserGroups domain) {
		UserGroupsModel model = new UserGroupsModel();
		model.setUsrGrpId(domain.getUsrGrpId());
		model.setUsrGrpName(domain.getUsrGrpName());
		model.setUsrGrpDesc(domain.getUsrGrpDesc());
		return model;
	}

}
