package com.lazz.ui.model;
// Generated Jul 22, 2018 7:33:01 PM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * UserDetails generated by hbm2java
 */
public class UserDetailsModel implements java.io.Serializable {

	private int usrdId;
	private UsersModel users;
	private String usrdFullName;
	private String usrdShpAddr1;
	private String usrdShpAddr2;
	private String usrdPostCode;
	private String usrdCity;
	private String usrdMob;
	private String usrdEmail;
	private String usrdState;

	public UserDetailsModel() {
	}

	public UserDetailsModel(UsersModel users, String usrdFullName) {
		this.users = users;
		this.usrdFullName = usrdFullName;
	}

	public UserDetailsModel(UsersModel users, String usrdFullName, String usrdShpAddr1, String usrdShpAddr2, String usrdPostCode,
			String usrdCity, String usrdMob, String usrdEmail, String usrdState) {
		this.users = users;
		this.usrdFullName = usrdFullName;
		this.usrdShpAddr1 = usrdShpAddr1;
		this.usrdShpAddr2 = usrdShpAddr2;
		this.usrdPostCode = usrdPostCode;
		this.usrdCity = usrdCity;
		this.usrdMob = usrdMob;
		this.usrdEmail = usrdEmail;
		this.usrdState = usrdState;
	}

	public int getUsrdId() {
		return this.usrdId;
	}

	public void setUsrdId(int usrdId) {
		this.usrdId = usrdId;
	}

	public UsersModel getUsers() {
		return this.users;
	}

	public void setUsers(UsersModel users) {
		this.users = users;
	}

	public String getUsrdFullName() {
		return this.usrdFullName;
	}

	public void setUsrdFullName(String usrdFullName) {
		this.usrdFullName = usrdFullName;
	}

	public String getUsrdShpAddr1() {
		return this.usrdShpAddr1;
	}

	public void setUsrdShpAddr1(String usrdShpAddr1) {
		this.usrdShpAddr1 = usrdShpAddr1;
	}

	public String getUsrdShpAddr2() {
		return this.usrdShpAddr2;
	}

	public void setUsrdShpAddr2(String usrdShpAddr2) {
		this.usrdShpAddr2 = usrdShpAddr2;
	}

	public String getUsrdPostCode() {
		return this.usrdPostCode;
	}

	public void setUsrdPostCode(String usrdPostCode) {
		this.usrdPostCode = usrdPostCode;
	}

	public String getUsrdCity() {
		return this.usrdCity;
	}

	public void setUsrdCity(String usrdCity) {
		this.usrdCity = usrdCity;
	}

	public String getUsrdMob() {
		return this.usrdMob;
	}

	public void setUsrdMob(String usrdMob) {
		this.usrdMob = usrdMob;
	}

	public String getUsrdEmail() {
		return this.usrdEmail;
	}

	public void setUsrdEmail(String usrdEmail) {
		this.usrdEmail = usrdEmail;
	}

	public String getUsrdState() {
		return this.usrdState;
	}

	public void setUsrdState(String usrdState) {
		this.usrdState = usrdState;
	}

}
