package com.lazz.service.domain;
// Generated Jul 22, 2018 7:33:01 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hq generated by hbm2java
 */
@Entity
@Table(name = "hq", catalog = "lazz_db_dev")
public class Hq implements java.io.Serializable {

	private Integer hqId;
	private String hqName;
	private String hqDesc;
	private String hqAddress;
	private Date createdDt;
	private Date updatedDt;

	public Hq() {
	}

	public Hq(String hqName, Date createdDt, Date updatedDt) {
		this.hqName = hqName;
		this.createdDt = createdDt;
		this.updatedDt = updatedDt;
	}

	public Hq(String hqName, String hqDesc, String hqAddress, Date createdDt, Date updatedDt) {
		this.hqName = hqName;
		this.hqDesc = hqDesc;
		this.hqAddress = hqAddress;
		this.createdDt = createdDt;
		this.updatedDt = updatedDt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "hq_id", unique = true, nullable = false)
	public Integer getHqId() {
		return this.hqId;
	}

	public void setHqId(Integer hqId) {
		this.hqId = hqId;
	}

	@Column(name = "hq_name", nullable = false, length = 50)
	public String getHqName() {
		return this.hqName;
	}

	public void setHqName(String hqName) {
		this.hqName = hqName;
	}

	@Column(name = "hq_desc", length = 100)
	public String getHqDesc() {
		return this.hqDesc;
	}

	public void setHqDesc(String hqDesc) {
		this.hqDesc = hqDesc;
	}

	@Column(name = "hq_address", length = 100)
	public String getHqAddress() {
		return this.hqAddress;
	}

	public void setHqAddress(String hqAddress) {
		this.hqAddress = hqAddress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_dt", nullable = false, length = 0)
	public Date getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_dt", nullable = false, length = 0)
	public Date getUpdatedDt() {
		return this.updatedDt;
	}

	public void setUpdatedDt(Date updatedDt) {
		this.updatedDt = updatedDt;
	}

}
