package com.lazz.service.domain;
// Generated Jul 22, 2018 7:33:01 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PrdPriceRules generated by hbm2java
 */
@Entity
@Table(name = "prd_price_rules", catalog = "lazz_db_dev")
public class PrdPriceRules implements java.io.Serializable {

	private Integer prdPrcRuleId;
	private ProdCfg prodCfg;
	private Integer prdPrcRuleCarton;
	private Float prdPrcRulePriceWest;
	private Float prdPrcRulePriceEast;
	private Date prdPrcRulePriceCrtdDt;
	private Date prdPrcRulePriceUptdDt;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "prd_prc_rule_id", unique = true, nullable = false)
	public Integer getPrdPrcRuleId() {
		return this.prdPrcRuleId;
	}

	public void setPrdPrcRuleId(Integer prdPrcRuleId) {
		this.prdPrcRuleId = prdPrcRuleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prd_cfg_id", nullable = false)
	public ProdCfg getProdCfg() {
		return this.prodCfg;
	}

	public void setProdCfg(ProdCfg prodCfg) {
		this.prodCfg = prodCfg;
	}

	@Column(name = "prd_prc_rule_carton")
	public Integer getPrdPrcRuleCarton() {
		return this.prdPrcRuleCarton;
	}

	public void setPrdPrcRuleCarton(Integer prdPrcRuleCarton) {
		this.prdPrcRuleCarton = prdPrcRuleCarton;
	}

	@Column(name = "prd_prc_rule_price_west", precision = 12, scale = 0)
	public Float getPrdPrcRulePriceWest() {
		return this.prdPrcRulePriceWest;
	}

	public void setPrdPrcRulePriceWest(Float prdPrcRulePriceWest) {
		this.prdPrcRulePriceWest = prdPrcRulePriceWest;
	}

	@Column(name = "prd_prc_rule_price_east", precision = 12, scale = 0)
	public Float getPrdPrcRulePriceEast() {
		return this.prdPrcRulePriceEast;
	}

	public void setPrdPrcRulePriceEast(Float prdPrcRulePriceEast) {
		this.prdPrcRulePriceEast = prdPrcRulePriceEast;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "prd_prc_rule_price_crtd_dt", nullable = false, length = 0)
	public Date getPrdPrcRulePriceCrtdDt() {
		return this.prdPrcRulePriceCrtdDt;
	}

	public void setPrdPrcRulePriceCrtdDt(Date prdPrcRulePriceCrtdDt) {
		this.prdPrcRulePriceCrtdDt = prdPrcRulePriceCrtdDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "prd_prc_rule_price_uptd_dt", nullable = false, length = 0)
	public Date getPrdPrcRulePriceUptdDt() {
		return this.prdPrcRulePriceUptdDt;
	}

	public void setPrdPrcRulePriceUptdDt(Date prdPrcRulePriceUptdDt) {
		this.prdPrcRulePriceUptdDt = prdPrcRulePriceUptdDt;
	}

}
