package com.lazz.service.domain;
// Generated Jul 22, 2018 7:33:01 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ProdCfg generated by hbm2java
 */
@Entity
@Table(name = "prod_cfg", catalog = "lazz_db_dev", uniqueConstraints = @UniqueConstraint(columnNames = { "prd_id",
		"usr_grp_id" }))
public class ProdCfg implements java.io.Serializable {

	private Integer prdCfgId;
	private Products products;
	private UserGroups userGroups;
	private Date prdCfgUptdDt;
	private Set<PrdPriceRules> prdPriceRuleses = new HashSet<PrdPriceRules>(0);
//	private Set<InvoiceDetails> invoiceDetailses = new HashSet<InvoiceDetails>(0);

	/*public ProdCfg() {
	}
*/
	/*public ProdCfg(Products products, UserGroups userGroups, Date prdCfgUptdDt) {
		this.products = products;
		this.userGroups = userGroups;
		this.prdCfgUptdDt = prdCfgUptdDt;
	}

	public ProdCfg(Products products, UserGroups userGroups, Date prdCfgUptdDt, Set prdPriceRuleses,
			Set invoiceDetailses) {
		this.products = products;
		this.userGroups = userGroups;
		this.prdCfgUptdDt = prdCfgUptdDt;
		this.prdPriceRuleses = prdPriceRuleses;
		this.invoiceDetailses = invoiceDetailses;
	}*/

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "prd_cfg_id", unique = true, nullable = false)
	public Integer getPrdCfgId() {
		return this.prdCfgId;
	}

	public void setPrdCfgId(Integer prdCfgId) {
		this.prdCfgId = prdCfgId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "prd_id", nullable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "usr_grp_id", nullable = false)
	public UserGroups getUserGroups() {
		return this.userGroups;
	}

	public void setUserGroups(UserGroups userGroups) {
		this.userGroups = userGroups;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "prd_cfg_uptd_dt", nullable = false, length = 0)
	public Date getPrdCfgUptdDt() {
		return this.prdCfgUptdDt;
	}

	public void setPrdCfgUptdDt(Date prdCfgUptdDt) {
		this.prdCfgUptdDt = prdCfgUptdDt;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((products == null) ? 0 : products.getPrdId().hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ProdCfg other = (ProdCfg) obj;
		if (products == null) {
			if (other.products != null)
				return false;
		} else if (products.getPrdId().intValue() != other.products.getPrdId().intValue())
			return false;
		return true;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "prodCfg")
	public Set<PrdPriceRules> getPrdPriceRuleses() {
		return this.prdPriceRuleses;
	}

	public void setPrdPriceRuleses(Set<PrdPriceRules> prdPriceRuleses) {
		this.prdPriceRuleses = prdPriceRuleses;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "prodCfg")
	public Set<InvoiceDetails> getInvoiceDetailses() {
		return this.invoiceDetailses;
	}

	public void setInvoiceDetailses(Set<InvoiceDetails> invoiceDetailses) {
		this.invoiceDetailses = invoiceDetailses;
	}*/

	
}
