package com.lazz.service.domain;
// Generated Jul 22, 2018 7:33:01 PM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * UserDetails generated by hbm2java
 */
@Entity
@Table(name = "user_details", catalog = "lazz_db_dev")
public class UserDetails implements java.io.Serializable {

	private int usrdId;
	private Users users;
	private String usrdFullName;
	private String usrdShpAddr1;
	private String usrdShpAddr2;
	private String usrdPostCode;
	private String usrdCity;
	private String usrdMob;
	private String usrdEmail;
	private String usrdState;

	public UserDetails() {
	}

	public UserDetails(Users users, String usrdFullName) {
		this.users = users;
		this.usrdFullName = usrdFullName;
	}

	public UserDetails(Users users, String usrdFullName, String usrdShpAddr1, String usrdShpAddr2, String usrdPostCode,
			String usrdCity, String usrdMob, String usrdEmail, String usrdState) {
		this.users = users;
		this.usrdFullName = usrdFullName;
		this.usrdShpAddr1 = usrdShpAddr1;
		this.usrdShpAddr2 = usrdShpAddr2;
		this.usrdPostCode = usrdPostCode;
		this.usrdCity = usrdCity;
		this.usrdMob = usrdMob;
		this.usrdEmail = usrdEmail;
		this.usrdState = usrdState;
	}

	@Id
    @GeneratedValue(generator = "foreigngen")
    @GenericGenerator(strategy = "foreign", name="foreigngen",
            parameters = @Parameter(name = "property", value="users"))
	@Column(name = "usr_id", unique = true, nullable = false)
	public int getUsrdId() {
		return this.usrdId;
	}

	public void setUsrdId(int usrdId) {
		this.usrdId = usrdId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "usrd_full_name", nullable = false, length = 50)
	public String getUsrdFullName() {
		return this.usrdFullName;
	}

	public void setUsrdFullName(String usrdFullName) {
		this.usrdFullName = usrdFullName;
	}

	@Column(name = "usrd_shp_addr_1", length = 50)
	public String getUsrdShpAddr1() {
		return this.usrdShpAddr1;
	}

	public void setUsrdShpAddr1(String usrdShpAddr1) {
		this.usrdShpAddr1 = usrdShpAddr1;
	}

	@Column(name = "usrd_shp_addr_2", length = 50)
	public String getUsrdShpAddr2() {
		return this.usrdShpAddr2;
	}

	public void setUsrdShpAddr2(String usrdShpAddr2) {
		this.usrdShpAddr2 = usrdShpAddr2;
	}

	@Column(name = "usrd_post_code", length = 50)
	public String getUsrdPostCode() {
		return this.usrdPostCode;
	}

	public void setUsrdPostCode(String usrdPostCode) {
		this.usrdPostCode = usrdPostCode;
	}

	@Column(name = "usrd_city", length = 50)
	public String getUsrdCity() {
		return this.usrdCity;
	}

	public void setUsrdCity(String usrdCity) {
		this.usrdCity = usrdCity;
	}

	@Column(name = "usrd_mob", length = 50)
	public String getUsrdMob() {
		return this.usrdMob;
	}

	public void setUsrdMob(String usrdMob) {
		this.usrdMob = usrdMob;
	}

	@Column(name = "usrd_email", length = 50)
	public String getUsrdEmail() {
		return this.usrdEmail;
	}

	public void setUsrdEmail(String usrdEmail) {
		this.usrdEmail = usrdEmail;
	}

	@Column(name = "usrd_state", length = 50)
	public String getUsrdState() {
		return this.usrdState;
	}

	public void setUsrdState(String usrdState) {
		this.usrdState = usrdState;
	}

}
