package com.lazz.service.domain;
// Generated Jul 22, 2018 7:33:01 PM by Hibernate Tools 5.2.10.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "lazz_db_dev", uniqueConstraints = @UniqueConstraint(columnNames = "usr_name"))
public class Users implements java.io.Serializable {

	private Integer usrId;
	private UserGroups userGroups;
	private UserTypes userTypes;
	private Users users;
	private String usrName;
	private String usrPassword;
	private Date usrCrtdDt;
	private Date usrUptdDt;
	private Set<Users> userses = new HashSet<Users>(0);
	private Set<Invoice> invoices = new HashSet<Invoice>(0);
//	private UserDetails userDetails;
	private String usrdFullName;
	private String usrdShpAddr1;
	private String usrdShpAddr2;
	private String usrdPostCode;
	private String usrdCity;
	private String usrdMob;
	private String usrdEmail;
	private String usrdState;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "usr_id", unique = true, nullable = false)
	public Integer getUsrId() {
		return this.usrId;
	}

	public void setUsrId(Integer usrId) {
		this.usrId = usrId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "usr_grp_id")
	public UserGroups getUserGroups() {
		return this.userGroups;
	}

	public void setUserGroups(UserGroups userGroups) {
		this.userGroups = userGroups;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ut_id", nullable = false)
	public UserTypes getUserTypes() {
		return this.userTypes;
	}

	public void setUserTypes(UserTypes userTypes) {
		this.userTypes = userTypes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usr_wrk_undr")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "usr_name", unique = true, nullable = false, length = 50)
	public String getUsrName() {
		return this.usrName;
	}

	public void setUsrName(String usrName) {
		this.usrName = usrName;
	}

	@Column(name = "usr_password", nullable = false, length = 50)
	public String getUsrPassword() {
		return this.usrPassword;
	}

	public void setUsrPassword(String usrPassword) {
		this.usrPassword = usrPassword;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "usr_crtd_dt", nullable = false, length = 0)
	public Date getUsrCrtdDt() {
		return this.usrCrtdDt;
	}

	public void setUsrCrtdDt(Date usrCrtdDt) {
		this.usrCrtdDt = usrCrtdDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "usr_uptd_dt", nullable = false, length = 0)
	public Date getUsrUptdDt() {
		return this.usrUptdDt;
	}

	public void setUsrUptdDt(Date usrUptdDt) {
		this.usrUptdDt = usrUptdDt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

	/*@OneToOne(fetch = FetchType.LAZY, mappedBy = "users", 
			cascade = CascadeType.ALL)
	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}*/

	@Column(name = "usrd_full_name", nullable = false, length = 50)
	public String getUsrdFullName() {
		return this.usrdFullName;
	}

	public void setUsrdFullName(String usrdFullName) {
		this.usrdFullName = usrdFullName;
	}

	@Column(name = "usrd_shp_addr_1", length = 50)
	public String getUsrdShpAddr1() {
		return this.usrdShpAddr1;
	}

	public void setUsrdShpAddr1(String usrdShpAddr1) {
		this.usrdShpAddr1 = usrdShpAddr1;
	}

	@Column(name = "usrd_shp_addr_2", length = 50)
	public String getUsrdShpAddr2() {
		return this.usrdShpAddr2;
	}

	public void setUsrdShpAddr2(String usrdShpAddr2) {
		this.usrdShpAddr2 = usrdShpAddr2;
	}

	@Column(name = "usrd_post_code", length = 50)
	public String getUsrdPostCode() {
		return this.usrdPostCode;
	}

	public void setUsrdPostCode(String usrdPostCode) {
		this.usrdPostCode = usrdPostCode;
	}

	@Column(name = "usrd_city", length = 50)
	public String getUsrdCity() {
		return this.usrdCity;
	}

	public void setUsrdCity(String usrdCity) {
		this.usrdCity = usrdCity;
	}

	@Column(name = "usrd_mob", length = 50)
	public String getUsrdMob() {
		return this.usrdMob;
	}

	public void setUsrdMob(String usrdMob) {
		this.usrdMob = usrdMob;
	}

	@Column(name = "usrd_email", length = 50)
	public String getUsrdEmail() {
		return this.usrdEmail;
	}

	public void setUsrdEmail(String usrdEmail) {
		this.usrdEmail = usrdEmail;
	}

	@Column(name = "usrd_state", length = 50)
	public String getUsrdState() {
		return this.usrdState;
	}

	public void setUsrdState(String usrdState) {
		this.usrdState = usrdState;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usrId")
	public Set<Invoice> getInvoices() {
		return invoices;
	}

	public void setInvoices(Set<Invoice> invoices) {
		this.invoices = invoices;
	}
	
	

}
