package com.lazz.service.domain;
// Generated Jul 22, 2018 7:33:01 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserTypes generated by hbm2java
 */
@Entity
@Table(name = "user_types", catalog = "lazz_db_dev")
public class UserTypes implements java.io.Serializable {

	private Integer utId;
	private String utName;
	private String utDesc;
	private Set<Users> userses = new HashSet<Users>(0);

	public UserTypes() {
	}

	public UserTypes(String utName) {
		this.utName = utName;
	}

	public UserTypes(String utName, String utDesc, Set userses) {
		this.utName = utName;
		this.utDesc = utDesc;
		this.userses = userses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ut_id", unique = true, nullable = false)
	public Integer getUtId() {
		return this.utId;
	}

	public void setUtId(Integer utId) {
		this.utId = utId;
	}

	@Column(name = "ut_name", nullable = false, length = 50)
	public String getUtName() {
		return this.utName;
	}

	public void setUtName(String utName) {
		this.utName = utName;
	}

	@Column(name = "ut_desc", length = 100)
	public String getUtDesc() {
		return this.utDesc;
	}

	public void setUtDesc(String utDesc) {
		this.utDesc = utDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTypes")
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
