package com.lazz.service.domain;
// Generated Jul 22, 2018 7:33:01 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserGroups generated by hbm2java
 */
@Entity
@Table(name = "user_groups", catalog = "lazz_db_dev")
public class UserGroups implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer usrGrpId;
	private String usrGrpName;
	private String usrGrpDesc;
	private Date usrCrtdDt;
	private Date usrUptdDt;
	private Set<ProdCfg> prodCfgs = new HashSet<ProdCfg>(0);
	private Set<Users> userses = new HashSet<Users>(0);

	/*public UserGroups() {
	}

	public UserGroups(String usrGrpName, Date usrCrtdDt, Date usrUptdDt) {
		this.usrGrpName = usrGrpName;
		this.usrCrtdDt = usrCrtdDt;
		this.usrUptdDt = usrUptdDt;
	}

	public UserGroups(String usrGrpName, String usrGrpDesc, Date usrCrtdDt, Date usrUptdDt, Set prodCfgs, Set userses) {
		this.usrGrpName = usrGrpName;
		this.usrGrpDesc = usrGrpDesc;
		this.usrCrtdDt = usrCrtdDt;
		this.usrUptdDt = usrUptdDt;
		this.prodCfgs = prodCfgs;
		this.userses = userses;
	}
	
	public UserGroups(String usrGrpName, String usrGrpDesc, Date usrCrtdDt, Date usrUptdDt, Set prodCfgs) {
		this.usrGrpName = usrGrpName;
		this.usrGrpDesc = usrGrpDesc;
		this.usrCrtdDt = usrCrtdDt;
		this.usrUptdDt = usrUptdDt;
		//this.prodCfgs = prodCfgs;
		this.userses = userses;
	}*/


	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "usr_grp_id", unique = true, nullable = false)
	public Integer getUsrGrpId() {
		return this.usrGrpId;
	}

	public void setUsrGrpId(Integer usrGrpId) {
		this.usrGrpId = usrGrpId;
	}

	@Column(name = "usr_grp_name", nullable = false, length = 50)
	public String getUsrGrpName() {
		return this.usrGrpName;
	}

	public void setUsrGrpName(String usrGrpName) {
		this.usrGrpName = usrGrpName;
	}

	@Column(name = "usr_grp_desc", length = 100)
	public String getUsrGrpDesc() {
		return this.usrGrpDesc;
	}

	public void setUsrGrpDesc(String usrGrpDesc) {
		this.usrGrpDesc = usrGrpDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "usr_crtd_dt", nullable = false, length = 0)
	public Date getUsrCrtdDt() {
		return this.usrCrtdDt;
	}

	public void setUsrCrtdDt(Date usrCrtdDt) {
		this.usrCrtdDt = usrCrtdDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "usr_uptd_dt", nullable = false, length = 0)
	public Date getUsrUptdDt() {
		return this.usrUptdDt;
	}

	public void setUsrUptdDt(Date usrUptdDt) {
		this.usrUptdDt = usrUptdDt;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "userGroups")
	public Set<ProdCfg> getProdCfgs() {
		return this.prodCfgs;
	}

	public void setProdCfgs(Set<ProdCfg> prodCfgs) {
		this.prodCfgs = prodCfgs;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "userGroups")
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
